def _require(namespace: dict[str, object], key: str) -> object:
    if key not in namespace:
        raise KeyError(key)
    return namespace[key]


def build_fetch_actor_notebook_deps_core(
    *,
    namespace: dict[str, object],
    source_tier: str | None = None,
    min_confidence_weight: int | None = None,
    source_days: int | None = None,
    prefer_cached: bool = True,
    build_on_cache_miss: bool = True,
    allow_stale_cache: bool = False,
) -> dict[str, object]:
    quick_check_service = _require(namespace, 'quick_check_service')
    return {
        'pipeline_fetch_actor_notebook_core': _require(namespace, 'pipeline_fetch_actor_notebook_core'),
        'db_path': _require(namespace, '_db_path'),
        'source_tier': source_tier,
        'min_confidence_weight': min_confidence_weight,
        'source_days': source_days,
        'prefer_cached': prefer_cached,
        'build_on_cache_miss': build_on_cache_miss,
        'allow_stale_cache': allow_stale_cache,
        'parse_published_datetime': _require(namespace, '_parse_published_datetime'),
        'safe_json_string_list': _require(namespace, '_safe_json_string_list'),
        'actor_signal_categories': _require(namespace, '_actor_signal_categories'),
        'question_actor_relevance': _require(namespace, '_question_actor_relevance'),
        'priority_update_evidence_dt': _require(namespace, '_priority_update_evidence_dt'),
        'question_org_alignment': _require(namespace, '_question_org_alignment'),
        'priority_rank_score': _require(namespace, '_priority_rank_score'),
        'phase_label_for_question': _require(namespace, '_phase_label_for_question'),
        'priority_where_to_check': _require(namespace, '_priority_where_to_check'),
        'priority_confidence_label': _require(namespace, '_priority_confidence_label'),
        'quick_check_title': _require(namespace, '_quick_check_title'),
        'short_decision_trigger': _require(namespace, '_short_decision_trigger'),
        'telemetry_anchor_line': _require(namespace, '_telemetry_anchor_line'),
        'priority_next_best_action': _require(namespace, '_priority_next_best_action'),
        'guidance_line': _require(namespace, '_guidance_line'),
        'guidance_query_hint': _require(namespace, '_guidance_query_hint'),
        'priority_disconfirming_signal': _require(namespace, '_priority_disconfirming_signal'),
        'confidence_change_threshold_line': _require(namespace, '_confidence_change_threshold_line'),
        'escalation_threshold_line': _require(namespace, '_escalation_threshold_line'),
        'expected_output_line': _require(namespace, '_expected_output_line'),
        'priority_update_recency_label': _require(namespace, '_priority_update_recency_label'),
        'org_alignment_label': _require(namespace, '_org_alignment_label'),
        'fallback_priority_questions': _require(namespace, '_fallback_priority_questions'),
        'token_overlap': _require(namespace, '_token_overlap'),
        'build_actor_profile_from_mitre': _require(namespace, '_build_actor_profile_from_mitre'),
        'group_top_techniques': _require(namespace, '_group_top_techniques'),
        'favorite_attack_vectors': _require(namespace, '_favorite_attack_vectors'),
        'known_technique_ids_for_entity': _require(namespace, '_known_technique_ids_for_entity'),
        'emerging_techniques_from_timeline': _require(namespace, '_emerging_techniques_from_timeline'),
        'build_timeline_graph': _require(namespace, '_build_timeline_graph'),
        'compact_timeline_rows': _require(namespace, '_compact_timeline_rows'),
        'actor_terms': _require(namespace, '_actor_terms'),
        'build_recent_activity_highlights': _require(namespace, '_build_recent_activity_highlights'),
        'build_top_change_signals': _require(namespace, 'pipeline_build_top_change_signals'),
        'ollama_review_change_signals': _require(namespace, '_ollama_review_change_signals'),
        'ollama_synthesize_recent_activity': _require(namespace, '_ollama_synthesize_recent_activity'),
        'enforce_ollama_synthesis': _require(namespace, 'ENFORCE_OLLAMA_SYNTHESIS'),
        'build_recent_activity_synthesis': _require(namespace, '_build_recent_activity_synthesis'),
        'recent_change_summary': _require(namespace, '_recent_change_summary'),
        'build_environment_checks': _require(namespace, '_build_environment_checks'),
        'build_notebook_kpis': _require(namespace, '_build_notebook_kpis'),
        'format_date_or_unknown': _require(namespace, '_format_date_or_unknown'),
        'load_source_reliability_map': _require(namespace, '_load_source_reliability_map'),
        'domain_from_url': _require(namespace, '_domain_from_url'),
        'confidence_weight_adjustment': _require(namespace, '_confidence_weight_adjustment'),
        'load_quick_check_overrides': (
            lambda connection, actor: quick_check_service.load_quick_check_overrides_core(
                connection,
                actor_id=actor,
            )
        ),
        'run_cold_actor_backfill': _require(namespace, 'run_cold_actor_backfill'),
        'rebuild_notebook': _require(namespace, 'build_notebook'),
        'backfill_debug_ui_enabled': _require(namespace, 'BACKFILL_DEBUG_UI'),
    }


def build_router_registration_deps_core(*, namespace: dict[str, object]) -> dict[str, object]:
    return {
        'routes_dashboard': _require(namespace, 'routes_dashboard'),
        'routes_api': _require(namespace, 'routes_api'),
        'routes_ui': _require(namespace, 'routes_ui'),
        'routes_actor_ops': _require(namespace, 'routes_actor_ops'),
        'routes_notebook': _require(namespace, 'routes_notebook'),
        'routes_evolution': _require(namespace, 'routes_evolution'),
        'list_actor_profiles': _require(namespace, 'list_actor_profiles'),
        'fetch_actor_notebook': _require(namespace, '_fetch_actor_notebook'),
        'set_actor_notebook_status': _require(namespace, 'set_actor_notebook_status'),
        'run_actor_generation': _require(namespace, 'run_actor_generation'),
        'enqueue_actor_generation': _require(namespace, 'enqueue_actor_generation'),
        'metrics_snapshot': _require(namespace, 'metrics_service').snapshot_metrics_core,
        'get_ollama_status': _require(namespace, 'get_ollama_status'),
        'page_refresh_auto_trigger_minutes': _require(namespace, 'PAGE_REFRESH_AUTO_TRIGGER_MINUTES'),
        'running_stale_recovery_minutes': _require(namespace, 'RUNNING_STALE_RECOVERY_MINUTES'),
        'recover_stale_running_states': _require(namespace, '_recover_stale_running_states'),
        'format_duration_ms': _require(namespace, '_format_duration_ms'),
        'templates': _require(namespace, 'templates'),
        'enforce_request_size': _require(namespace, '_enforce_request_size'),
        'default_body_limit_bytes': _require(namespace, 'DEFAULT_BODY_LIMIT_BYTES'),
        'create_actor_profile': _require(namespace, 'create_actor_profile'),
        'merge_actor_profiles': _require(namespace, 'merge_actor_profiles'),
        'db_path': _require(namespace, '_db_path'),
        'actor_exists': _require(namespace, 'actor_exists'),
        'source_upload_body_limit_bytes': _require(namespace, 'SOURCE_UPLOAD_BODY_LIMIT_BYTES'),
        'derive_source_from_url': _require(namespace, 'derive_source_from_url'),
        'upsert_source_for_actor': _require(namespace, '_upsert_source_for_actor'),
        'import_default_feeds_for_actor': _require(namespace, 'import_default_feeds_for_actor'),
        'parse_ioc_values': _require(namespace, '_parse_ioc_values'),
        'validate_ioc_candidate': _require(namespace, '_validate_ioc_candidate'),
        'upsert_ioc_item': _require(namespace, '_upsert_ioc_item'),
        'export_actor_stix_bundle': _require(namespace, '_export_actor_stix_bundle'),
        'import_actor_stix_bundle': _require(namespace, '_import_actor_stix_bundle'),
        'list_ranked_evidence': _require(namespace, '_list_ranked_evidence'),
        'sync_taxii_collection': _require(namespace, '_sync_taxii_collection'),
        'list_taxii_sync_runs': _require(namespace, '_list_taxii_sync_runs'),
        'taxii_collection_url': _require(namespace, '_taxii_collection_url'),
        'taxii_auth_token': _require(namespace, '_taxii_auth_token'),
        'taxii_lookback_hours': _require(namespace, 'TAXII_LOOKBACK_HOURS'),
        'utc_now_iso': _require(namespace, 'utc_now_iso'),
        'get_actor_refresh_stats': _require(namespace, 'get_actor_refresh_stats'),
        'get_actor_refresh_timeline': _require(namespace, 'get_actor_refresh_timeline'),
        'submit_actor_refresh_job': _require(namespace, 'submit_actor_refresh_job'),
        'get_actor_refresh_job': _require(namespace, 'get_actor_refresh_job'),
        'generate_actor_requirements': _require(namespace, 'generate_actor_requirements'),
        'safe_json_string_list': _require(namespace, '_safe_json_string_list'),
        'generate_ioc_hunt_queries': _require(namespace, '_ollama_generate_ioc_hunt_queries'),
        'store_feedback_event': _require(namespace, '_store_feedback_event'),
        'feedback_summary_for_actor': _require(namespace, '_feedback_summary_for_actor'),
        'normalize_environment_profile': _require(namespace, '_normalize_environment_profile'),
        'upsert_environment_profile': _require(namespace, '_upsert_environment_profile'),
        'load_environment_profile': _require(namespace, '_load_environment_profile'),
        'apply_feedback_to_source_domains': _require(namespace, '_apply_feedback_to_source_domains'),
        'get_tracking_intent': _require(namespace, 'get_tracking_intent'),
        'upsert_tracking_intent': _require(namespace, 'upsert_tracking_intent'),
        'confirm_actor_assessment': _require(namespace, 'confirm_actor_assessment'),
        'dispatch_alert_deliveries': _require(namespace, 'dispatch_alert_deliveries'),
        'observation_body_limit_bytes': _require(namespace, 'OBSERVATION_BODY_LIMIT_BYTES'),
        'normalize_technique_id': _require(namespace, '_normalize_technique_id'),
        'normalize_string_list': _require(namespace, 'normalize_string_list'),
        'capability_category_from_technique_id': _require(namespace, '_capability_category_from_technique_id'),
        'generate_validation_template': _require(namespace, 'generate_validation_template'),
        'baseline_entry': _require(namespace, 'baseline_entry'),
        'resolve_delta_action': (
            lambda actor_id, delta_id, requested_action: namespace['resolve_delta_action'](
                actor_id,
                delta_id,
                requested_action,
            )
        ),
    }


def build_feed_import_deps_core(
    *,
    namespace: dict[str, object],
    max_seconds: int | None = None,
    import_mode: str = 'background',
    high_signal_target: int | None = None,
) -> dict[str, object]:
    return {
        'pipeline_import_default_feeds_for_actor_core': _require(namespace, 'pipeline_import_default_feeds_for_actor_core'),
        'db_path': lambda: namespace['DB_PATH'],
        'default_cti_feeds': _require(namespace, 'DEFAULT_CTI_FEEDS'),
        'primary_cti_feeds': _require(namespace, 'PRIMARY_CTI_FEEDS') + _require(namespace, 'EXPANDED_PRIMARY_ADVISORY_FEEDS'),
        'secondary_context_feeds': _require(namespace, 'SECONDARY_CONTEXT_FEEDS'),
        'actor_feed_lookback_days': _require(namespace, 'ACTOR_FEED_LOOKBACK_DAYS'),
        'feed_import_max_seconds': (
            max(10, int(max_seconds))
            if max_seconds is not None
            else _require(namespace, 'FEED_IMPORT_MAX_SECONDS')
        ),
        'feed_fetch_timeout_seconds': _require(namespace, 'FEED_FETCH_TIMEOUT_SECONDS'),
        'feed_entry_scan_limit': _require(namespace, 'FEED_ENTRY_SCAN_LIMIT'),
        'feed_imported_limit': _require(namespace, 'FEED_IMPORTED_LIMIT'),
        'feed_soft_match_limit': _require(namespace, 'FEED_SOFT_MATCH_LIMIT'),
        'actor_search_link_limit': _require(namespace, 'ACTOR_SEARCH_LINK_LIMIT'),
        'feed_require_published_at': _require(namespace, 'FEED_REQUIRE_PUBLISHED_AT'),
        'evidence_pipeline_v2': _require(namespace, 'EVIDENCE_PIPELINE_V2'),
        'feed_import_mode': str(import_mode or 'background'),
        'feed_high_signal_target': (
            max(1, int(high_signal_target))
            if high_signal_target is not None
            else _require(namespace, 'FEED_INTERACTIVE_HIGH_SIGNAL_TARGET')
        ),
        'retain_soft_candidates': _require(namespace, 'FEED_RETAIN_SOFT_CANDIDATES'),
        'actor_exists': _require(namespace, 'actor_exists'),
        'build_actor_profile_from_mitre': _require(namespace, '_build_actor_profile_from_mitre'),
        'actor_terms': _require(namespace, '_actor_terms'),
        'actor_query_feeds': _require(namespace, '_actor_query_feeds'),
        'import_ransomware_live_actor_activity': _require(namespace, '_import_ransomware_live_actor_activity'),
        'safe_http_get': _require(namespace, '_safe_http_get'),
        'parse_feed_entries': _require(namespace, '_parse_feed_entries'),
        'text_contains_actor_term': _require(namespace, '_text_contains_actor_term'),
        'within_lookback': _require(namespace, '_within_lookback'),
        'parse_published_datetime': _require(namespace, '_parse_published_datetime'),
        'derive_source_from_url': _require(namespace, 'derive_source_from_url'),
        'upsert_source_for_actor': _require(namespace, '_upsert_source_for_actor'),
        'duckduckgo_actor_search_urls': _require(namespace, '_duckduckgo_actor_search_urls'),
        'utc_now_iso': _require(namespace, 'utc_now_iso'),
        'source_trust_score': _require(namespace, '_source_trust_score'),
    }
